CREATE SCHEMA IF NOT EXISTS hksr;

CREATE TABLE IF NOT EXISTS hksr.sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL,
    external_id text NOT NULL,
    source_kind text NOT NULL,
    page_url text NOT NULL,
    title text NOT NULL DEFAULT '',
    version text,
    official_status text NOT NULL DEFAULT 'unknown',
    status text NOT NULL DEFAULT 'discovered',
    content_sha256 text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    discovered_at timestamptz NOT NULL DEFAULT now(),
    fetched_at timestamptz,
    parsed_at timestamptz,
    UNIQUE (provider, external_id)
);

CREATE TABLE IF NOT EXISTS hksr.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id bigint NOT NULL REFERENCES hksr.sources(id) ON DELETE CASCADE,
    document_key text NOT NULL,
    title text NOT NULL,
    section_path text NOT NULL,
    content_type text NOT NULL,
    position integer NOT NULL,
    evidence_eligible boolean NOT NULL DEFAULT true,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (source_id, document_key)
);

CREATE TABLE IF NOT EXISTS hksr.chunks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint NOT NULL REFERENCES hksr.documents(id) ON DELETE CASCADE,
    chunk_key text NOT NULL,
    evidence_id text NOT NULL UNIQUE,
    section_path text NOT NULL,
    speaker text NOT NULL DEFAULT '',
    text text NOT NULL,
    position integer NOT NULL,
    content_sha256 text NOT NULL,
    embedding vector(1024),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    synthetic boolean NOT NULL DEFAULT false CHECK (synthetic = false),
    UNIQUE (document_id, chunk_key)
);

CREATE TABLE IF NOT EXISTS hksr.entities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name text NOT NULL,
    entity_type text NOT NULL,
    description text NOT NULL DEFAULT '',
    UNIQUE (canonical_name, entity_type)
);

CREATE TABLE IF NOT EXISTS hksr.aliases (
    entity_id bigint NOT NULL REFERENCES hksr.entities(id) ON DELETE CASCADE,
    alias text NOT NULL,
    alias_type text NOT NULL DEFAULT 'official',
    PRIMARY KEY (entity_id, alias)
);

CREATE TABLE IF NOT EXISTS hksr.entity_chunks (
    entity_id bigint NOT NULL REFERENCES hksr.entities(id) ON DELETE CASCADE,
    chunk_id bigint NOT NULL REFERENCES hksr.chunks(id) ON DELETE CASCADE,
    matched_text text NOT NULL,
    PRIMARY KEY (entity_id, chunk_id)
);

CREATE TABLE IF NOT EXISTS hksr.relations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id bigint NOT NULL REFERENCES hksr.entities(id) ON DELETE CASCADE,
    predicate text NOT NULL,
    object_id bigint NOT NULL REFERENCES hksr.entities(id) ON DELETE CASCADE,
    evidence_level text NOT NULL,
    review_status text NOT NULL,
    confidence double precision NOT NULL DEFAULT 1.0,
    reasoning text NOT NULL DEFAULT '',
    origin text NOT NULL DEFAULT 'curated',
    is_stale boolean NOT NULL DEFAULT false,
    UNIQUE (subject_id, predicate, object_id, origin)
);

CREATE TABLE IF NOT EXISTS hksr.relation_evidence (
    relation_id bigint NOT NULL REFERENCES hksr.relations(id) ON DELETE CASCADE,
    evidence_id text NOT NULL REFERENCES hksr.chunks(evidence_id) ON DELETE RESTRICT,
    note text NOT NULL DEFAULT '',
    PRIMARY KEY (relation_id, evidence_id)
);

CREATE TABLE IF NOT EXISTS hksr.ingestion_state (
    state_key text PRIMARY KEY,
    value jsonb NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS chunks_document_position_idx ON hksr.chunks(document_id, position);
CREATE INDEX IF NOT EXISTS chunks_content_sha256_idx ON hksr.chunks(content_sha256);
CREATE INDEX IF NOT EXISTS relations_subject_status_idx ON hksr.relations(subject_id, review_status);
CREATE INDEX IF NOT EXISTS relations_object_status_idx ON hksr.relations(object_id, review_status);
