ALTER TABLE hksr.sources ADD COLUMN IF NOT EXISTS sqlite_id bigint;
ALTER TABLE hksr.documents ADD COLUMN IF NOT EXISTS sqlite_id bigint;
ALTER TABLE hksr.chunks ADD COLUMN IF NOT EXISTS sqlite_id bigint;
ALTER TABLE hksr.entities ADD COLUMN IF NOT EXISTS sqlite_id bigint;
ALTER TABLE hksr.relations ADD COLUMN IF NOT EXISTS sqlite_id bigint;

CREATE UNIQUE INDEX IF NOT EXISTS sources_sqlite_id_idx
    ON hksr.sources(sqlite_id) WHERE sqlite_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS documents_sqlite_id_idx
    ON hksr.documents(sqlite_id) WHERE sqlite_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS chunks_sqlite_id_idx
    ON hksr.chunks(sqlite_id) WHERE sqlite_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS entities_sqlite_id_idx
    ON hksr.entities(sqlite_id) WHERE sqlite_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS relations_sqlite_id_idx
    ON hksr.relations(sqlite_id) WHERE sqlite_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS hksr.source_dispositions (
    source_id bigint PRIMARY KEY REFERENCES hksr.sources(id) ON DELETE CASCADE,
    disposition text NOT NULL,
    reason text NOT NULL,
    classifier_version text NOT NULL,
    verified boolean NOT NULL,
    reviewed_at timestamptz,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS hksr.chunk_vectors (
    chunk_id bigint PRIMARY KEY REFERENCES hksr.chunks(id) ON DELETE CASCADE,
    vector_json jsonb NOT NULL,
    norm double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS hksr.retrieval_metadata (
    key text PRIMARY KEY,
    value jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS hksr.narrative_people (
    stable_key text PRIMARY KEY,
    canonical_name text NOT NULL UNIQUE,
    description text NOT NULL DEFAULT '',
    schema_version integer NOT NULL
);

CREATE TABLE IF NOT EXISTS hksr.playable_forms (
    stable_key text PRIMARY KEY,
    narrative_person_key text NOT NULL
        REFERENCES hksr.narrative_people(stable_key) ON DELETE RESTRICT,
    entity_id bigint NOT NULL UNIQUE REFERENCES hksr.entities(id) ON DELETE RESTRICT,
    canonical_name text NOT NULL,
    form_kind text NOT NULL CHECK (form_kind IN ('base', 'alternate')),
    link_status text NOT NULL CHECK (link_status IN ('approved', 'pending', 'rejected')),
    evidence_id text,
    schema_version integer NOT NULL,
    UNIQUE (narrative_person_key, canonical_name)
);

CREATE TABLE IF NOT EXISTS hksr.identity_names (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_kind text NOT NULL CHECK (owner_kind IN ('person', 'form')),
    owner_key text NOT NULL,
    name text NOT NULL,
    name_type text NOT NULL CHECK (
        name_type IN ('canonical', 'official_alias', 'punctuation_variant', 'player_shorthand')
    ),
    is_official boolean NOT NULL,
    evidence_id text,
    schema_version integer NOT NULL,
    UNIQUE (owner_kind, owner_key, name)
);

CREATE INDEX IF NOT EXISTS source_dispositions_state_idx
    ON hksr.source_dispositions(disposition, verified);
CREATE INDEX IF NOT EXISTS aliases_alias_idx ON hksr.aliases(alias);
CREATE INDEX IF NOT EXISTS chunks_text_bigm_idx ON hksr.chunks
    USING gin(text gin_bigm_ops);
CREATE INDEX IF NOT EXISTS chunks_section_bigm_idx ON hksr.chunks
    USING gin(section_path gin_bigm_ops);
CREATE INDEX IF NOT EXISTS entity_chunks_chunk_idx ON hksr.entity_chunks(chunk_id);
CREATE INDEX IF NOT EXISTS entity_chunks_entity_idx ON hksr.entity_chunks(entity_id, chunk_id);
CREATE INDEX IF NOT EXISTS playable_forms_person_idx
    ON hksr.playable_forms(narrative_person_key, link_status);
CREATE INDEX IF NOT EXISTS identity_names_name_idx
    ON hksr.identity_names(name, owner_kind);

ALTER TABLE hksr.import_batches
    DROP CONSTRAINT IF EXISTS import_batches_batch_id_check;
ALTER TABLE hksr.import_batches
    ADD CONSTRAINT import_batches_batch_id_check
    CHECK (batch_id ~ '^m(6b|7|10)-real-[a-z0-9][a-z0-9-]{2,59}$');
